### PR TITLE
Modify code to accomodate Echo V2

### PR DESCRIPTION
**Pull request by rtuin**
Should close: https://github.com/olebedev/go-starter-kit/issues/54

All credits go to @phuongvu. This commit was cherry-picked from that fork.

@olebedev I'm not sure how to update the `srlt.yaml` file. Can you explain how I should do that?

### CODE REVIEW

**Comment by olebedev** [comment]
hi @rtuin,

it's as simple as a cake. Just need to drop [these](https://github.com/rtuin/go-starter-kit/blob/7f9ca026fa58aa1a22092a5fc9bea144ed1d0145/srlt.yaml#L83-L87) lines and run `srlt s`. Make sure that `./vendor/gopkg.in/labstack/echo.v2` installed and have `.git` folder.

**Comment by rtuin** [comment]
Thanks @olebedev. I've added the updated `srlt.yaml` file now!

**Comment by olebedev** [comment]
@rtuin 

looks good to me. Only two things have to ask you to change: 
- get rid of [`github.com/dgrijalva/jwt-go`](https://github.com/olebedev/go-starter-kit/pull/55/files#diff-5f07c64c7581596d6f8b5de5e702af6bR8), since it's have not been used
- drop [`e.Use(middleware.Gzip())`](https://github.com/olebedev/go-starter-kit/pull/55/files#diff-fc5afeec8fce01fa85ed0ce5e20f32c0R63) line, since, actually, the best practice is to use _nginx_  for this kind of issues.

**Comment by rtuin** [comment]
Thanks for taking a look. I'll probably have time to look at this again on
Monday!

**Comment by phuongvu** [comment]
Hey @rtuin, I'm glad that you find my fork useful!

**Comment by joelnb** [comment]
If anyone is still interested in this I made a version which works with the new vendoring scheme: https://github.com/joelnb/go-starter-kit/tree/echo.v2

I also had a look at supporting echo v3 which is out now but there are quite a few changes and I haven't yet got it working.

**Comment by olebedev** [comment]
@joelnb, thanks for the attempt. It would be definitely good to have the dependecies updated. Looking forward for a new PR!

**Comment by joelnb** [comment]
@olebedev take a look at https://github.com/olebedev/go-starter-kit/pull/65 for a version which uses the latest version of echo & updates all the other dependencies.

**Pull request closed without merging**
