### PR TITLE
Fix for: Update npm dependencies

### PR DESCRIPTION
**Pull request by franklinkim**
This should do it. There was sth with the react-router.
I also re-added the devtools since i forgot to add them the last time.

I had to comment out this block:

```
  if (process.env.NODE_ENV !== 'production'){
    store.subscribe(() => {
      console.log('%c[STORE]', 'color: green', store.getState());
    });
  }
```

since it keeps on logging due to the devtools.

### CODE REVIEW

**Comment by olebedev** [comment]
@franklinkim thanks! 
I had just reverted your previous PR. Could you resolve the conflicts manually, please?

**Comment by olebedev** [comment]
This block was added before devtool and i forgot to remove it. Or cause it should be deleted.

**Comment by franklinkim** [comment]
ok, merge your current master and removed the block. might wanna recheck before merging :P

**Comment by olebedev** [comment]
Thanks! I was a good idea to check it before merge ) Not critical, I had to fixed `react-router` warning produced at the server in the render moment. Take a look: https://github.com/olebedev/go-starter-kit/commit/b2ddbac124ff56e77f6679daec3b4e787d423338.

**Comment by franklinkim** [comment]
ah nice, missed that one while merging and didn't see the error. thx!

**Pull request merged**
