### PR TITLE
fix versions of packages in srlt

### PR DESCRIPTION
**Pull request by matsu911**

### CODE REVIEW

**Comment by olebedev** [comment]
Hi @matsu911,

is `github.com/valyala/fasttemplate` necessary?

**Comment by matsu911** [comment]
Hi @olebedev,

The latest gommon requires it.
https://github.com/labstack/gommon/commit/81aef43cee03d40e9190983caeb70343a68d7f76

Thanks.

**Comment by olebedev** [comment]
Clear. 
Unfortunately, we don't have tests here. Did you test the project? It works well with updated echo/gommon package?

**Comment by olebedev** [comment]
I have checked it manually it works, thanks @matsu911.

**Comment by matsu911** [comment]
Thanks

**Pull request merged**
