### PR TITLE
Update npm dependencies

### PR DESCRIPTION
**Pull request by franklinkim**
Hi, just taken your starter kit for a test drive and updated the npm dependencies.

### CODE REVIEW

**Comment by olebedev** [comment]
Hi @franklinkim,
thanks for the update. Could you move `.babelrc` back into `package.json` file? I had made it two days ago and the project has become less verbose and more intuitive for gophers.

**Comment by franklinkim** [comment]
Sure :)

**Comment by olebedev** [comment]
:+1:

**Comment by olebedev** [comment]
Hi @franklinkim, 

I have got errors with this update:
```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).warning @ warning.js?0260:45ReactElementValidator.createElement @ ReactElementValidator.js?a599:221run @ index.js?9347:27(anonymous function) @ index.js?8956:9(anonymous function) @ index.js?8956:7(anonymous function) @ bundle.js:1988__webpack_require__ @ bundle.js:521fn @ bundle.js:76(anonymous function) @ bundle.js:575__webpack_require__ @ bundle.js:521(anonymous function) @ bundle.js:544(anonymous function) @ bundle.js:547
invariant.js?568c:39 Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```
and the app is totally broken. Could you fix the issue or it's better ro revert PR?

**Comment by franklinkim** [comment]
hi, sorry about that! will see if i can reproduce that and fix it.

**Comment by franklinkim** [comment]
I sent you another pull request based on this one. guess it didn't merge here cause i deleted my old branch...

**Pull request merged**
